inherit_from: .rubocop_todo.yml

Layout/ArgumentAlignment:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/Lambda:
  EnforcedStyle: literal

Style/ClassAndModuleChildren:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: 'end'

# Disabled to allow the outdented comment style
Layout/CommentIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

Naming/PredicateName:
  Enabled: false
